// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using DaxAmmonsFinalProject.Data;

#nullable disable

namespace DaxAmmonsFinalProject.Migrations
{
    [DbContext(typeof(StatsContext))]
    [Migration("20220425200734_Stats")]
    partial class Stats
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.4");

            modelBuilder.Entity("DaxAmmonsFinalProject.Models.Stats", b =>
                {
                    b.Property<int>("StatsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Strength")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Speed")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Intelligence")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Charisma")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Armor")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.HasKey("StatsId");

                    b.ToTable("Stats");
                });
#pragma warning restore 612, 618
        }
    }
}